### ISSUE TITLE
This is a terrible video

### ISSUE THREAD

**Issue by benlimpic** [learn-co-curriculum/phase-1-lecture-videos-map-part-2#3]
### Canvas Link

https://learning.flatironschool.com/courses/5171/pages/video-map-part-2?module_item_id=375742

### Concern

I feel really bothered by the lack of quality in this tutorial. If this was simply on youtube people would be roasting it in the comments for being insane and hard to understand. It is very difficult for me to feel comfortable with this type of instruction as I learned this concept 10X easier with Codecademy for almost free. How is this type of content supposed to make me feel about my massive investment into this short course? This threw all kinds of red flags for me and I am very concerned about how the rest of my instruction will be moving forward. 

### Additional Context

My classmates were equally concerned with the lack of care and quality in this video.

### Suggested Changes

I feel like if I hadn't seen these videos at all I would be more confident in where my education is headed with Flatiron. Someone needs to remove these and remake them for the good of the students at flatiron.

**Comment by lizbur10** [comment]
Hi @benlimpic - I'm sorry to hear this! Could you provide a little more specific information about what isn't working for you? That will make it easier for us to address your concerns when we update the video.

Thanks.

**Comment by lizbur10** [comment]
Hi @benlimpic ! I'm going to go ahead and close this issue at this time, but if you have additional details you'd like to share with us, please feel free to reopen it 💙
